<?php

use Illuminate\Database\Seeder;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        
        DB::table('codigos')->insert(['codigo'=>'FhVF6','activa'=>1]);
        DB::table('codigos')->insert(['codigo'=>'3J52T','activa'=>1]);
        DB::table('codigos')->insert(['codigo'=>'RpImG','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'8DQwY','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'Wckh6','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'gS266','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'4pqen','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'TfaLN','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'MiQMO','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'H6HBR','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'TEqxu','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'Idh4U','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'cpvPu','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'CIrTi','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'7dWgU','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'4XWVG','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'ZMwFe','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'Tzkub','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'sk79H','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'TM0Q3','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'6RbFg','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'SKTkp','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'7DuIh','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'NhUn9','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'ZsQFp','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'nN9dY','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'cD27L','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'JQsHy','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'4q4iq','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'qQ5WI','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'ty2vw','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'4v8HJ','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'9Oabr','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'hFOOz','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'QoOR9','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'bSrsR','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'g00pP','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'AQIwg','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'fYiJK','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'DOUKx','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'w7qYK','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'TnMui','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'341OL','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'IpcwW','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'cdamH','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'n2QYZ','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'rbB9e','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'WbZ6F','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'byvDx','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'xLsTV','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'gzp63','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'8O7WA','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'Y4I8k','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'tUUSC','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'YAtEw','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'ePJ8t','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'51hJk','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'l2DSL','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'s98EI','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'6VDE1','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'7HgUh','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'Let7A','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'Qp36T','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'cuuKQ','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'Me2zU','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'thQhM','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'0hPwv','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'KkyMN','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'4TEGN','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'tlE2o','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'v6dCl','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'aFo5A','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'5ODgT','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'JjneI','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'gqs4J','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'ervQ1','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'KKafg','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'duthy','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'Wcs6c','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'rtSLv','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'ISZCa','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'UV3nR','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'nuCIG','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'Ly74L','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'FIVxl','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'xayoj','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'jFGsm','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'w7Y2C','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'Aw0iN','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'lt6tA','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'83dgP','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'6YKKl','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'P1LIZ','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'dTMJW','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'jgUxf','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'vUF53','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'vVYy6','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'WuepU','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'vv0kI','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'JIgiR','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'Z8ftv','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'LSx87','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'VCYJv','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'vgnTA','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'Tgo9P','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'rjYc4','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'e07Bg','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'J1f89','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'U6LK0','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'cRhGw','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'tw34Q','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'2baq0','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'CUF2c','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'WQ2kZ','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'KIv9j','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'bjjNk','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'6tY60','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'zknLh','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'Ph4Ie','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'upsR3','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'rJJZi','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'u2C0a','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'EvTn3','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'rlGPr','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'7xZu8','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'CGBxY','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'IfMWi','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'EVVcQ','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'GvJDa','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'BIGhc','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'BCImd','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'EcLhi','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'aLxo4','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'86jQa','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'DjWcP','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'wOYho','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'ob6Kn','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'E3MJj','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'tnQk4','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'m2nBh','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'a5PX4','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'dycDq','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'jIbG9','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'iFUis','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'3fbwt','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'0ZcS1','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'GmUBp','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'Gb0Xp','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'A0veY','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'1mEmg','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'VARTE','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'qIMk3','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'lp4Ll','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'XpyMD','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'2YYW2','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'ZsO6o','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'pb08v','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'AFdw2','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'JK0CP','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'ORYy0','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'O5Y8z','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'tXub3','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'zbS3e','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'iBsXM','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'8CgmU','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'aPUZb','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'4ehqG','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'0pKNB','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'KrV8h','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'z8Sa1','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'kak1A','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'PzmeM','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'jQF4I','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'WejRt','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'zhoa4','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'w9P7p','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'EStBt','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'vmyA5','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'FyBmm','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'6LMGW','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'osIQQ','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'7WEHu','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'8vKMC','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'HPw94','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'qxc2x','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'h8ODd','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'SmiXm','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'SfG0l','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'gzGcQ','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'NKSKI','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'p5dwt','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'1yYqG','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'UTcLA','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'0IGfj','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'NwQNM','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'ssCgI','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'ndKOW','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'SmcQP','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'dPgvh','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'I4qRd','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'NurQS','activa'=>0]);
        DB::table('codigos')->insert(['codigo'=>'Ol2Ko','activa'=>0]);



        



    }
}